name: riedenv
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - pytest
    - numpy
    - scipy
    - scikit-learn
    - matplotlib
    - sklearn
    - pytorch
    - pip
    - pandas
    - flask=2.2.2
    - pip:
        - gmsh
        - graphviz
        - lime
        - sympy
        - iteration_utilities
        - autograd
        - pymoo
